name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.6
  share_plus: ^7.2.1
  # Added missing dependencies for your weather app
  geolocator: ^12.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env